apiVersion: v1
kind: Service
metadata:
  name: yapster-metrics
  namespace: yapster
  labels:
    app: yapster-metrics
spec:
  selector:
    app: yapster-backend
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
