# mongo-headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: yapster
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
