apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yapster-metrics-monitor
  namespace: yapster
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: yapster-metrics
  namespaceSelector:
    matchNames:
      - yapster
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
