
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: yapster
  labels:
    app: jenkins
    component: token
  annotations:
    kubernetes.io/service-account.name: jenkins
    description: "Authentication token for Jenkins service account"
type: kubernetes.io/service-account-token
